### ISSUE TITLE
Task: Service-object

### ISSUE THREAD

**Issue by vovs03** [vovs03/Todoser#4]
# Service-object

У нас теперь есть обобщенный результат выполнение сервис обжекта, теперь нам нужен собственно создать костяк этого сервис обжекта

1)  [x] 1 Подтянуть все свежие изменения  по ветке master
2) [x] 2 Создать новую ветку `service-object`
3) [x] 3 в папке `app/services` создать файл `service.rb`
4) [x] 4 Создать в нем класс `Service`
5) [x] 5 Так как мы в сервисах всегда будем создавать результаты выполнения и они будут двух видов, то лучше создать в них сразу методы хелперы, 
  - 1ый метод `success(data)` который просто создает `Result.new(true,data,nil)` и 
  - второй метод `failure(error_message, data = nil)` (просто не всегда нужно будет передавать этот параметр) `Result.new(false, data, error_messages)`
1. [x] 6 Написать тесты (RSpec) на класс `Service`

**Comment by vovs03** [comment]
Был не понятен пункт 5.

пункт5 class Service почти копия класса Result? (Yoda помог)

**Comment by vovs03** [comment]
- ❓Именование методов(хэлперов) в данном случае они уже будут `без вопросительного знака в конце имени`, так?

> Предположу, что позже `error_message` будет задействован и не надо обращать внимание на совет линтера.

`Unused method argument - `error_message`. If it's necessary, use `_` or `_error_message` as an argument name to indicate that it won't be used. (warning:Lint/UnusedMethodArgument)`

![Screenshot 2022-05-24 at 19 33 48](https://user-images.githubusercontent.com/21124057/170088665-c788d9d2-0437-4fdf-83ac-148f18f8eac8.jpg)

**Comment by XaoGao** [comment]
Входным параметром в метод у тебя идет "error_message" а в result ты передаешь "error_messages" ошибка в наименовании

**Comment by vovs03** [comment]
## Именование аргументов

> - Есть ли зависимость между именованиями аргументов для `N`-классов ?
>  - s = Service.new(data, `error_message`) и Result.new(false, data, `error_messages`)
> - Имена аргументов в обоих классов должны быть идентичными? 

@XaoGao я такое название аргумента взял из таски, что прислано в телеграме. Так как правильно должен именоваться аргумент?
  - 🅰️ : `error_message`
  - 🅱️ : `error_messages`

**Comment by vovs03** [comment]
##  Взаимодействие классов

@XaoGao Как я понимаю, мы передаём из класса`Result.new(false, data, error_messages)` [14 строка]

### Перенос данных между переменными методов

Хочу понять механизм: т.к. переменная метода конструктора `@error_messaages = error_messages` (Вчера только заметил опечатку https://github.com/XaoGao/Todoser/issues/4) находится в классе `Result` а нам надо передать её значение в переменную конструктора класса`Service` отсюда и вопрос озвученный выше (обязательна ли идентичность именований аргументов в обоих классах? https://github.com/vovs03/Todoser/issues/4#issuecomment-1136758043)

**Comment by XaoGao** [comment]
Вопрос не принципиальный, давай сойдешьмся что в Service#failure передается  "error_messages"  и в Result классе тоже будет везде (в attr_reader и в конструкторе) "error_messages"
